"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type Employee = { id: string; candidateId?: string | null; employeeNo: string; firstName: string; lastName: string; email: string; jobTitle: string; department?: string | null; status: string };
type SelectedCandidate = { id: string; referenceNo: string; firstName: string; lastName: string; email: string; phone: string; roleOfInterest: string; status: string; source: string };

export default function EmployeesPage() {
  const [items, setItems] = useState<Employee[]>([]);
  const [selected, setSelected] = useState<SelectedCandidate[]>([]);
  const [message, setMessage] = useState("Loading employees…");
  const [feedback, setFeedback] = useState("");
  const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); setMessage(""); const [employeeResponse, selectedResponse] = await Promise.all([fetch("/api/v1/employees?page=1&pageSize=50"), fetch("/api/v1/candidates?status=SELECTED&page=1&pageSize=100")]); const employeeResult = await employeeResponse.json(); const selectedResult = await selectedResponse.json(); if (!employeeResponse.ok) { setLoading(false); return setMessage(employeeResult.error?.message || "Could not load employees"); } if (!selectedResponse.ok) { setLoading(false); return setMessage(selectedResult.error?.message || "Could not load selected hires"); } setItems(employeeResult.data.items); setSelected(selectedResult.data.items); setLoading(false); }
  useEffect(() => { void load(); }, []);
  async function addToOnboarding(employeeId: string) { setFeedback("Adding employee to onboarding…"); const response = await fetch("/api/v1/onboarding", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ employeeId }) }); const result = await response.json(); setFeedback(response.ok ? "Employee added to onboarding." : result.error?.message || "Could not add employee to onboarding"); }
  return <main className="page-shell"><section className="panel employees-page-panel"><div className="section-heading"><div><p className="eyebrow">Employee lifecycle</p><h1>Employees</h1><p className="page-intro">Manage selected hires and employee records from one workspace.</p></div></div><div className="employees-toolbar toolbar"><button className="employees-refresh-button" type="button" onClick={() => void load()}>Refresh employees</button><Link className="employees-onboarding-button" href="/hr/onboarding">Onboarding dashboard</Link></div>{loading && <p role="status" className="loading-state">Loading employee workspace…</p>}{message && <p role="alert">{message}</p>}{feedback && <p role="status">{feedback}</p>}{!loading && !message && <><section className="employee-section"><div className="section-heading"><div><p className="eyebrow">Selected hires</p><h2>Selected candidates</h2></div><span className="section-count">{selected.length}</span></div>{selected.length ? <div className="candidate-list">{selected.map((candidate) => { const employee = items.find((item) => item.candidateId === candidate.id); const employeePreviewHref = employee ? `/hr/employees/${employee.id}` : `/hr/employees/selected/${candidate.id}`; return <div className="candidate-row selected-candidate-row" key={candidate.id}><Link className="selected-candidate-name" href={employeePreviewHref}><strong>{candidate.firstName} {candidate.lastName}</strong><small>{candidate.referenceNo}</small></Link><span><strong>{candidate.roleOfInterest || "Position not specified"}</strong><small>{candidate.email} · {candidate.phone}</small></span><span><strong>{candidate.status}</strong><small>{candidate.source === "WALK_IN" ? "Walk-in form" : "Social media form"}</small></span><Link className="candidate-preview-button" href={employeePreviewHref}>Preview employee</Link></div>; })}</div> : <p className="empty-state">No selected candidates found.</p>}</section><section className="employee-section"><div className="section-heading"><div><p className="eyebrow">Employee directory</p><h2>Employee records</h2></div><span className="section-count">{items.length}</span></div>{items.length ? <div className="candidate-list">{items.map((employee) => <div className="candidate-row employee-directory-row" key={employee.id}><Link className="employee-directory-link" href={`/hr/employees/${employee.id}`}><strong>{employee.employeeNo} · {employee.firstName} {employee.lastName}</strong><small>{employee.jobTitle} · {employee.department || "No department"} · {employee.status}</small><small>{employee.email}</small></Link><button className="candidate-preview-button" type="button" onClick={() => void addToOnboarding(employee.id)}>Add to onboarding</button></div>)}</div> : <p className="empty-state">No employee records found.</p>}</section></>}</section></main>;
}
