"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Task = { id: string; status: string; dueDate: string | null; notes: string | null; definition: { title: string; description: string | null; category: string | null; required: boolean } };
type Detail = { id: string; status: string; employee: { id: string; employeeNo: string; firstName: string; lastName: string; email: string; jobTitle: string; joiningDate: string }; template: { name: string }; progress: { percent: number; completed: number; total: number; overdue: number; requiredComplete: boolean }; tasks: Task[]; documents: Array<{ id: string; kind: string; fileName: string; status: string; acknowledged: boolean }> };
const phaseOrder = ["PRE_JOINING", "COMPLIANCE", "DAY_ONE", "CONNECTION", "ROLE", "MILESTONE"];

export default function OnboardingDetail({ params }: { params: Promise<{ id: string }> }) {
  const [item, setItem] = useState<Detail | null>(null);
  const [message, setMessage] = useState("Loading onboarding…");
  const [notes, setNotes] = useState<Record<string, string>>({});
  async function load() { const values = await params; const response = await fetch(`/api/v1/onboarding/${values.id}`); const result = await response.json(); if (!response.ok) return setMessage(result.error?.message || "Could not load onboarding"); setItem(result.data); setMessage(""); }
  useEffect(() => { void load(); }, []);
  async function complete(taskId: string) { if (!item) return; const response = await fetch(`/api/v1/onboarding/${item.id}/tasks/${taskId}/complete`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ notes: notes[taskId] || undefined }) }); const result = await response.json(); if (!response.ok) return setMessage(result.error?.message || "Could not complete task"); setNotes((current) => ({ ...current, [taskId]: "" })); await load(); }
  if (!item) return <main className="page-shell"><section className="panel"><p role="status">{message}</p></section></main>;
  const grouped = phaseOrder.map((phase) => ({ phase, tasks: item.tasks.filter((task) => (task.definition.category || "PRE_JOINING") === phase) })).filter((group) => group.tasks.length);
  return <main className="page-shell"><section className="panel employees-page-panel"><Link href="/hr/onboarding">← Back to onboarding</Link><div className="section-heading onboarding-detail-heading"><div><p className="eyebrow">Onboarding plan</p><h1>{item.employee.firstName} {item.employee.lastName}</h1><p className="page-intro">{item.employee.employeeNo} · {item.employee.jobTitle} · starts {new Date(item.employee.joiningDate).toLocaleDateString()}</p></div><span className={`status-pill ${item.status.toLowerCase()}`}>{item.status.replace("_", " ")}</span></div><div className="onboarding-hero"><div><span>Overall progress</span><strong>{item.progress.percent}%</strong><small>{item.progress.completed} of {item.progress.total} tasks complete · {item.progress.overdue} overdue</small></div><div className="onboarding-progress large"><i style={{ width: `${item.progress.percent}%` }} /></div><div><span>Required work</span><strong>{item.progress.requiredComplete ? "Ready" : "In progress"}</strong><small>{item.employee.email}</small></div></div>{message && <p role="status">{message}</p>}<div className="onboarding-columns"><div>{grouped.map((group) => <section className="onboarding-phase" key={group.phase}><div className="section-heading"><h2>{group.phase.replace("_", " ")}</h2><small>{group.tasks.filter((task) => task.status === "COMPLETED").length}/{group.tasks.length} complete</small></div>{group.tasks.map((task) => <article className={`onboarding-task ${task.status.toLowerCase()}`} key={task.id}><div className="task-check">{task.status === "COMPLETED" ? "✓" : "○"}</div><div className="task-copy"><strong>{task.definition.title}{task.definition.required && <em>Required</em>}</strong><p>{task.definition.description || "No additional instructions."}</p><small>{task.dueDate ? `Due ${new Date(task.dueDate).toLocaleDateString()}` : "No due date"} · {task.status.replace("_", " ")}</small>{task.status !== "COMPLETED" && <div className="task-action"><input placeholder="Completion note (optional)" value={notes[task.id] || ""} onChange={(event) => setNotes((current) => ({ ...current, [task.id]: event.target.value }))} /><button type="button" onClick={() => void complete(task.id)}>Mark complete</button></div>}</div></article>)}</section>)}</div><aside><h2>Required documents</h2>{item.documents.length ? item.documents.map((document) => <div className="onboarding-document" key={document.id}><strong>{document.kind.replaceAll("_", " ")}</strong><small>{document.fileName}</small><span>{document.status.replace("_", " ")}</span></div>) : <p className="empty-state">No onboarding documents requested.</p>}<Link className="button-link" href={`/hr/employees/${item.employee.id}`}>Open employee record</Link></aside></div></section></main>;
}
