export const PAYROLL_PERMISSIONS = {
  salaryRead: "salary.read",
  salaryManage: "salary.manage",
  payrollRead: "payroll.read",
  payrollManage: "payroll.manage",
  payrollReview: "payroll.review",
  payrollApprove: "payroll.approve",
  payslipsGenerate: "payslips.generate",
  payslipsDownload: "payslips.download",
  expensesSubmit: "expenses.submit",
  expensesRead: "expenses.read",
  expensesApprove: "expenses.approve",
  expensesPay: "expenses.pay",
  reports: "payroll.reports",
} as const;
