"use client";

import { useEffect, useState } from "react";

type Visit = { id: string; status: string; visitDate: string; checkedInAt?: string | null; checkedOutAt?: string | null; lateArrivalMinutes?: number | null; earlyDepartureMinutes?: number | null; exceptionType?: string | null; candidate: { firstName: string; lastName: string; referenceNo: string }; interview?: { referenceNo: string } | null; host?: { name: string } | null };

export default function AttendancePage() {
  const [items, setItems] = useState<Visit[]>([]);
  const [message, setMessage] = useState("Loading attendance…");
  async function load() { const response = await fetch("/api/v1/attendance?page=1&pageSize=50"); const result = await response.json(); if (!response.ok) return setMessage(result.error?.message || "Could not load attendance"); setItems(result.data.items); setMessage(result.data.items.length ? "" : "No attendance records found."); }
  async function updateVisit(id: string, action: "check-in" | "check-out") { const response = await fetch(`/api/v1/attendance/${action}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ visitId: id }) }); const result = await response.json(); if (!response.ok) return setMessage(result.error?.message || "Could not update attendance"); setItems((current) => current.map((item) => item.id === id ? result.data : item)); }
  async function addException(id: string) { const notes = window.prompt("Exception notes"); if (!notes?.trim()) return; const response = await fetch(`/api/v1/attendance/${id}/exception`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ exceptionType: "INVALID_ATTENDANCE_STATE", notes }) }); const result = await response.json(); if (!response.ok) return setMessage(result.error?.message || "Could not record exception"); setItems((current) => current.map((item) => item.id === id ? result.data : item)); }
  useEffect(() => { void load(); }, []);
  return <main className="page-shell"><section className="panel"><p className="eyebrow">Candidate attendance</p><h1>Attendance and visitor records</h1><div className="toolbar"><button type="button" onClick={() => void load()}>Refresh attendance</button><a href="/hr/visitors">Register visitor</a></div>{message && <p role="status">{message}</p>}<div className="candidate-list">{items.map((item) => <article className="candidate-row" key={item.id}><span>{item.candidate.firstName} {item.candidate.lastName} · {item.candidate.referenceNo}</span><span>{item.interview?.referenceNo || "Visitor"} · {item.host?.name || "No host"}</span><span>{item.status}{item.lateArrivalMinutes ? ` · ${item.lateArrivalMinutes}m late` : ""}{item.earlyDepartureMinutes ? ` · ${item.earlyDepartureMinutes}m early` : ""}</span><span>{item.status === "REGISTERED" && <button type="button" onClick={() => void updateVisit(item.id, "check-in")}>Check in</button>}{item.status === "CHECKED_IN" && <button type="button" onClick={() => void updateVisit(item.id, "check-out")}>Check out</button>}<button type="button" onClick={() => void addException(item.id)}>Record exception</button></span></article>)}</div></section></main>;
}
