"use client";

import { useEffect, useState } from "react";

type Detail = { id: string; employeeNo: string; firstName: string; lastName: string; email: string; phone: string; jobTitle: string; department?: string | null; location?: string | null; status: string; history: Array<{ id: string; eventType: string; fromValue?: string | null; toValue?: string | null; createdAt: string }>; onboardingInstances: Array<{ id: string; status: string; template: { name: string }; tasks: Array<{ id: string; status: string; definition: { title: string } }> }> };

export default function EmployeePage({ params }: { params: Promise<{ id: string }> }) {
  const [employee, setEmployee] = useState<Detail | null>(null);
  const [message, setMessage] = useState("Loading employee…");
  useEffect(() => { void (async () => { const values = await params; const response = await fetch(`/api/v1/employees/${values.id}`); const result = await response.json(); if (!response.ok) return setMessage(result.error?.message || "Could not load employee"); setEmployee(result.data); setMessage(""); })(); }, [params]);
  async function complete(onboardingId: string, taskId: string) { const response = await fetch(`/api/v1/onboarding/${onboardingId}/tasks/${taskId}/complete`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({}) }); const result = await response.json(); if (!response.ok) return setMessage(result.error?.message || "Could not complete task"); setMessage("Task completed"); setEmployee((current) => current ? { ...current, onboardingInstances: current.onboardingInstances.map((instance) => instance.id === onboardingId ? { ...instance, tasks: instance.tasks.map((task) => task.id === taskId ? { ...task, status: "COMPLETED" } : task) } : instance) } : current); }
  if (!employee) return <main className="page-shell"><section className="panel"><p role="status">{message}</p></section></main>;
  return <main className="page-shell"><section className="panel"><p className="eyebrow">Employee profile</p><h1>{employee.employeeNo} · {employee.firstName} {employee.lastName}</h1><p>{employee.jobTitle} · {employee.status}</p><dl className="details"><dt>Email</dt><dd>{employee.email}</dd><dt>Phone</dt><dd>{employee.phone}</dd><dt>Department</dt><dd>{employee.department || "Not provided"}</dd><dt>Location</dt><dd>{employee.location || "Not provided"}</dd></dl><h2>Onboarding</h2>{employee.onboardingInstances.map((instance) => <article className="panel" key={instance.id}><h3>{instance.template.name} · {instance.status}</h3><ul>{instance.tasks.map((task) => <li key={task.id}>{task.definition.title} · {task.status} {task.status !== "COMPLETED" && <button type="button" onClick={() => void complete(instance.id, task.id)}>Complete</button>}</li>)}</ul><a href={`/hr/onboarding/${instance.id}`}>Open onboarding</a></article>)}<h2>Employment history</h2><ul>{employee.history.map((item) => <li key={item.id}>{item.eventType} · {item.fromValue || ""} → {item.toValue || ""} · {new Date(item.createdAt).toLocaleString()}</li>)}</ul>{message && <p role="status">{message}</p>}</section></main>;
}
