"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Task = { status: string; dueDate: string | null; definition: { required: boolean } };
type Item = { id: string; status: string; employee: { employeeNo: string; firstName: string; lastName: string; status: string }; template: { name: string }; tasks: Task[]; documents: Array<{ status: string }> };
const filters = ["ALL", "PRE_JOINING", "IN_PROGRESS", "COMPLETED", "BLOCKED"];

export default function OnboardingPage() {
  const [items, setItems] = useState<Item[]>([]);
  const [filter, setFilter] = useState("ALL");
  const [message, setMessage] = useState("Loading onboarding…");
  async function load() { setMessage("Loading onboarding…"); const response = await fetch(`/api/v1/onboarding?page=1&pageSize=100${filter === "ALL" ? "" : `&status=${filter}`}`); const result = await response.json(); if (!response.ok) return setMessage(result.error?.message || "Could not load onboarding"); setItems(result.data.items); setMessage(""); }
  useEffect(() => { void load(); }, [filter]);
  const summary = useMemo(() => items.reduce((result, item) => { const completed = item.tasks.filter((task) => task.status === "COMPLETED").length; result.total += 1; result.completed += item.status === "COMPLETED" ? 1 : 0; result.tasks += completed; result.taskTotal += item.tasks.length; result.overdue += item.tasks.filter((task) => task.status === "OVERDUE").length; return result; }, { total: 0, completed: 0, tasks: 0, taskTotal: 0, overdue: 0 }), [items]);
  return <main className="page-shell"><section className="panel employees-page-panel"><div className="section-heading"><div><p className="eyebrow">Employee lifecycle</p><h1>Onboarding</h1><p className="page-intro">Prepare new employees before day one, guide their first 90 days, and keep every owner accountable.</p></div><button type="button" onClick={() => void load()}>Refresh</button></div><div className="dashboard-stats"><article><span>Active plans</span><strong>{summary.total - summary.completed}</strong><small>{summary.completed} completed</small></article><article><span>Task progress</span><strong>{summary.tasks}/{summary.taskTotal}</strong><small>{summary.overdue} overdue</small></article><article><span>Completion rate</span><strong>{summary.taskTotal ? Math.round((summary.tasks / summary.taskTotal) * 100) : 0}%</strong><small>Across visible plans</small></article></div><div className="toolbar onboarding-filters" aria-label="Filter onboarding plans">{filters.map((value) => <button className={filter === value ? "active" : ""} type="button" key={value} onClick={() => setFilter(value)}>{value === "ALL" ? "All plans" : value.replace("_", " ")}</button>)}</div>{message && <p role="status">{message}</p>}{!message && <div className="candidate-list">{items.map((item) => { const done = item.tasks.filter((task) => task.status === "COMPLETED").length; const percent = item.tasks.length ? Math.round((done / item.tasks.length) * 100) : 0; const documents = item.documents.filter((document) => document.status === "VERIFIED").length; return <Link className="candidate-row onboarding-row" href={`/hr/onboarding/${item.id}`} key={item.id}><span><strong>{item.employee.firstName} {item.employee.lastName}</strong><small>{item.employee.employeeNo} · {item.employee.status}</small></span><span><strong>{item.template.name}</strong><small>{done} of {item.tasks.length} tasks · {documents} verified documents</small></span><span><strong>{percent}%</strong><small>{item.status.replace("_", " ")}</small></span><span className="onboarding-progress"><i style={{ width: `${percent}%` }} /></span></Link>; })}{!items.length && <p className="empty-state">No onboarding plans match this filter.</p>}</div>}</section></main>;
}
